baseURL = "https://shendao.in/"
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
disablePathToLower = true
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[services.disqus]
shortname = 'cshintov'

[languages]
  [languages.en]
    title = "Ananke"
    weight = 1
    contentDir = "content/en"

  [languages.fr]
    title = "Ananke Fr"
    weight = 2
    contentDir = "content/fr"

[sitemap]
filename = "sitemap.xml"
changefreq = "monthly"
priority = 0.5

[params]
description = "My notes."
author = ""
favicon = ""
site_logo = ""
text_color = ""
background_color_class = ""  # "bg-black" from https://tachyons.io/docs/themes/skins/
recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/cshintov"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/cshintov"
